[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd delivery-optimization-frontend && npm install']

[phases.build]
cmds = ['cd delivery-optimization-frontend && npm run build']

[start]
cmd = 'cd delivery-optimization-frontend && npm run start'
