server:
  port: ${PORT:8081}

spring:
  application:
    name: petri-net-api

  r2dbc:
    url: r2dbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:petri_db}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 10
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    com.yowyob.petrinet: DEBUG
    org.springframework.data.r2dbc: DEBUG
